name = "bws-travel-proxy"
main = "worker.js"
compatibility_date = "2024-09-23"
account_id = "2c5caa1d8d06877cb21513a03fc0277e"

[observability]
enabled = true

[observability.logs]
invocation_logs = true

[[queues.producers]]
queue = "itinerary-queue"
binding = "ITINERARY_QUEUE"

[[queues.consumers]]
queue = "itinerary-queue"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 3

[[kv_namespaces]]
binding = "PREVIEW_STORE"
id = "a797f8ce8efe40ecab25b4429779d27f"
